<?php

declare(strict_types=1);

namespace Yiisoft\Yii\AuthClient\Client;

use Yiisoft\Yii\AuthClient\OAuth2;
use Yiisoft\Yii\AuthClient\OAuthToken;
use Yiisoft\Yii\AuthClient\RequestUtil;

/**
 * Date: 31/12/2024
 *
 * Google allows authentication via Google OAuth2 using HTTP client. Here we are NOT using the alternative Client Libraries
 * namely @see https://developers.google.com/people/v1/libraries#php
 * In order to use Google OAuth2 you must create a project at <https://console.cloud.google.com/cloud-resource-manager>
 * and setup its credentials at <https://console.cloud.google.com/apis/credentials?project=[yourProjectId]>.
 * Create an Oauth2 Web Application and record the resultant Client Id and Client Secret in e.g a .env file and insert your website's returnUrl e.g. https:\\example.com\callbackGoogle
 * @see Google+ Api is being shutdown https://developers.google.com/+/api-shutdown
 * @see https://developers.google.com/oauthplayground
 * @see <https://console.cloud.google.com/welcome?project=[yourProjectId]>
 */
class Google extends OAuth2 implements GoogleInterface
{
    protected string $authUrl = 'https://accounts.google.com/o/oauth2/v2/auth';
    protected string $tokenUrl = 'https://oauth2.googleapis.com/token';
    protected string $endPoint = 'https://www.googleapis.com/oauth2/v2/userinfo';

    public function getCurrentUserJsonArray(OAuthToken $token): array
    {
        /**
         * e.g. '{all the params}' => ''
         * @var array $params
         */
        $tokenParams = $token->getParams();

        /**
         * e.g. convert the above key, namely '{all the params}', into an array
         * @var array $tokenArray
         */
        $tokenArray = array_keys($tokenParams);

        /**
         * @var string $jsonString
         */
        $jsonString = $tokenArray[0];

        /**
         * @var array $finalArray
         */
        $finalArray = json_decode($jsonString, true);

        /**
         * @var string $tokenString
         */
        $tokenString = $finalArray['access_token'] ?? '';

        if (strlen($tokenString) > 0) {
            $request = $this->createRequest('GET', 'https://www.googleapis.com/oauth2/v2/userinfo');

            $request = RequestUtil::addHeaders(
                $request,
                [
                    'Authorization' => 'Bearer ' . $tokenString,
                    // Generated by oauthplayground
                    'Host' => 'www.googleapis.com',
                    // Generated by oauthplayground
                    'Content-length' => 0,
                ]
            );

            $response = $this->sendRequest($request);

            $user = [];

            return (array)json_decode($response->getBody()->getContents(), true);
        }

        return [];
    }

    /**
     * @return string service name.
     *
     * @psalm-return 'google'
     */
    public function getName(): string
    {
        return 'google';
    }

    /**
     * @return string service title.
     *
     * @psalm-return 'Google'
     */
    public function getTitle(): string
    {
        return 'Google';
    }

    /**
     * @see https://www.googleapis.com/auth/userinfo.profile will output userinfo.profile
     * @see https://www.googleapis.com/auth/userinfo.email will output userinfo.email
     * @psalm-return 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
     */
    #[\Override]
    protected function getDefaultScope(): string
    {
        return 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email';
    }

    /**
     * Previously:
     * @see https://www.googleapis.com/auth/people/me
     * ...which returns:
     *
     * ..."You are receiving this error either because
     * your input OAuth2 scope name is invalid or
     * it refers to a newer scope that is outside the domain of this legacy API.
     * This API was built at a time when the scope name format was not yet standardized.
     * This is no longer the case and all valid scope names (both old and new) are catalogued at
     * https://developers.google.com/identity/protocols/oauth2/scopes."
     *
     * Use that webpage to lookup (manually) the scope name associated with the API you are trying to call
     * and use it to craft your OAuth2 request.
     *
     * @see https://developers.google.com/identity/protocols/oauth2/scopes#oauth2
     *
     * ...which returns two scopes
     *
     * 1. https://www.googleapis.com/auth/userinfo.email  See your Primary Google Email Address
     * 2. https://www.googleapis.com/auth/userinfo.profile  See your personal info, including any personal info you've made publicly available
     */
}
