<?php

declare(strict_types=1);

namespace Yiisoft\Yii\AuthClient\Client;

use Psr\Http\Message\ServerRequestInterface;
use Yiisoft\Yii\AuthClient\Widget\GooglePlusButton;

/**
 * GoogleHybrid is an enhanced version of the {@see Google}, which uses Google+ hybrid sign-in flow,
 * which relies on embedded JavaScript code to generate a sign-in button and handle user authentication dialog.
 *
 * Note: Google+ hybrid relies heavily on client-side JavaScript during authorization process, do not attempt to
 * obtain authorization code using {@see buildAuthUrl()} unless you absolutely sure, what you are doing.
 *
 * JavaScript button itself generated by {@see \Yiisoft\Yii\AuthClient\Widget\GooglePlusButton}} widget. If you are using
 * {@see \Yiisoft\Yii\AuthClient\Widget\AuthChoice} it will appear automatically. Otherwise you need to add it into your page manually.
 *
 * @see Google
 * @see \Yiisoft\Yii\AuthClient\Widget\GooglePlusButton
 * @link https://developers.google.com/+/web/signin
 */
final class GoogleHybrid extends Google
{
    protected bool $validateAuthState = false;

    protected function defaultReturnUrl(ServerRequestInterface $request): string
    {
        return 'postmessage';
    }

    protected function defaultViewOptions(): array
    {
        return [
            'widget' => [
                'class' => GooglePlusButton::class,
            ],
        ];
    }
}
